// <auto-generated />
namespace PayAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class virtual_dict : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(virtual_dict));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061238430_virtual_dict"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
